### ISSUE TITLE
could not create Vfs.Dir from url, no matching UrlType

### ISSUE THREAD

**Issue by jwn-css** [vaadin/vaadin-gradle-plugin#115]
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: 11
 - Gradle version: 6.7
 - Vaadin Plugin version: 0.14.5.1

**Describe the bug**
Error / Exception on task "vaadinPrepareFrontend" 

**To Reproduce**
1. Setup vaadin project with dependencies other than *.jar
2. Run Gradle task "build"
4. See error:

_2021-05-29T18:38:04.517+0200 [WARN] [org.reflections.Reflections] could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/C:/Users/\<User\>/.gradle/caches/modules-2/files-2.1/com.microsoft.sqlserver/mssql-jdbc_auth/8.4.0.x64/90108f5fc6
0a177ac6ffcdd74a30dc68fd90b3f/**mssql-jdbc_auth-8.4.0.x64.dll**]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)
        at org.reflections.Reflections.scan(Reflections.java:240)
        at org.reflections.Reflections.scan(Reflections.java:202)
        at org.reflections.Reflections.<init>(Reflections.java:123)
        at com.vaadin.gradle.ReflectionsClassFinder.<init>(ReflectionsClassFinder.kt:49)
        at com.vaadin.gradle.VaadinUtilsKt.getClassFinder(VaadinUtils.kt:63)
        at com.vaadin.gradle.VaadinUtilsKt.createNodeTasksBuilder(VaadinUtils.kt:157)
        at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
       ...

**Expected behavior**
Exclude unsupported libraries when scanning frontend dependencies so that no exception is thrown

**Comment by mvysny** [comment]
Excellent catch, thank you! What kind of dependency is that please? `implementation("com.microsoft.sqlserver:mssql-jdbc_auth:8.4.0.x64")` ?

**Comment by jwn-css** [comment]
It is necessary for accessing MSSQL databases from Java applications on Windows systems.

**Comment by mvysny** [comment]
Could you please share your build.gradle?

**Comment by jwn-css** [comment]
The dependency comes from internal dependencies that we can't change at the moment. So I don't think this is really helpful. The error also occurs when the package is added to the Vaadin Gradle Starter project as a dependency. 
Wouldn't it be possible to check the dependencies in question for their file extension and only include jar's in the consideration?

**Comment by mvysny** [comment]
Yes that sounds like a good fix. However i need to reproduce the bug
locally first, in order to see whether the fix works. (And also to create a
test case for the plugin later on). Can you create a small project which
reproduces the issue please?

**Comment by jwn-css** [comment]
```
plugins {
    id 'war'
    id 'org.gretty' version '3.0.3'
    id 'com.vaadin' version '0.14.5.1'
}

defaultTasks("clean", "build")

repositories {
    mavenCentral()
    jcenter()
}

gretty {
    contextPath = "/"
    servletContainer = "jetty9.4"
}

vaadin {
    pnpmEnable = true
}

dependencies {
    implementation enforcedPlatform('com.vaadin:vaadin-bom:14.5.1')
    implementation("com.vaadin:vaadin-core") {
        ["com.vaadin.webjar", "org.webjars.bowergithub.insites",
         "org.webjars.bowergithub.polymer", "org.webjars.bowergithub.polymerelements",
         "org.webjars.bowergithub.vaadin", "org.webjars.bowergithub.webcomponents"]
                .forEach { group -> exclude(group: group) }
    }
    implementation("com.microsoft.sqlserver:mssql-jdbc_auth:8.4.0.x64")
    providedCompile "javax.servlet:javax.servlet-api:3.1.0"
    implementation "org.slf4j:slf4j-simple:1.7.30"
}
```

**Comment by mvysny** [comment]
Thank you, reproduced & fixed :+1:

**Comment by jwn-css** [comment]
Nice, thank you!
