### ISSUE TITLE
Gradle Plugin for Vaadin 23 compiled with JDK17, should be: JDK11

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-gradle-plugin#130]
`Cause: com/vaadin/gradle/VaadinPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
`
git@github.com:vaadin/base-starter-gradle.git
for v23

This is from my memory, and I may have made a mistake -- but please can you check. Thank you.

**Comment by mvysny** [comment]
The plugin for Vaadin 23 is located at https://github.com/vaadin/flow/, please open the bug report there.
