### ISSUE TITLE
configure Vaadin version to use

### ISSUE THREAD

**Issue by mdre** [vaadin/vaadin-gradle-plugin#40]
Consider adding a property to set the Vaadin Flow version to use. For example:

vaadinVersion=14.1.3

or 

vaadinVersion=14.+

**Comment by mstahv** [comment]
Hi,

Is there some specific reason why you'd want that custom property? In our examples we define the Vaadin version along with the bom:

https://github.com/vaadin/base-starter-gradle/blob/master/build.gradle#L24

I haven't tried ranges, like 14.+, but I guess those should work too.

cheers,
matti

**Comment by mdre** [comment]
Sorry, no. I could set the specific version in the dependency section so it is not important. 
The plugin work perfectly for now.
