### ISSUE TITLE
Document the Installation Process

### ISSUE THREAD

**Issue by realulim** [vaadin/vaadin-gradle-plugin#41]
How do I actually use this plugin? I tried:

```
plugins {
id 'com.vaadin.vaadin-gradle-plugin' version '0.5.0'
}
plugins {
id 'com.vaadin.gradle.vaadin-gradle-plugin' version '0.5.0'
}
```
But neither worked. Do I need to configure a special repository?

**Comment by magi42** [comment]
The ID is simply `com.vaadin`:
```
plugins {
    id 'com.vaadin' version '0.5.0'
}
```
There's an upcoming tutorial, which will be part of official Vaadin documentation: https://github.com/vaadin-learning-center/learning-content/blob/author/magi/gradle-plugin/learn/tutorials/gradle-plugin/content.adoc

**Comment by mstahv** [comment]
@realulim Where did you find those id? Just trying to figure our where we should put that in addition to the starter examples.

**Comment by realulim** [comment]
I didn't find them, I tried to infer them from the naming scheme used for the Maven plugin. I think you just need to put a paragraph about "installation" on the front page, because that is where those IDs are usually listed.
