### ISSUE TITLE
vaadinClean removes webpack config

### ISSUE THREAD

**Issue by realulim** [vaadin/vaadin-gradle-plugin#43]
I am not sure if this is a bug, because it seems fully intentional. But I would like to at least question the decision to remove webpack.config.js. It seems to me that this file is the place for user customisations. It says within the file:
```
 /**
  * This file has been autogenerated as it didn't exist or was made for an older incompatible version.
  * This file can be used for manual configuration will not be modified if the flowDefaults constant exists.
  */
```
So to me it seems wrong to remove this file on "clean". It is initially generated, but it is not a build artefact. It should be enough to remove the webpack.generated.js file.

**Comment by mvysny** [comment]
You're right, that sounds completely reasonable. Sounds like a quickie, I'll work on that.

**Comment by caalador** [comment]
Yes webpack.config.js is for developer usage so they can add their own modifications and we promise to only touch the wepack.generated.js.
