### ISSUE TITLE
Revise basic application project stubs

### ISSUE THREAD

**Issue by magi42** [vaadin/vaadin-gradle-plugin#5]
The logic in the basic application stubs is a bit odd and confusing; pushing a button creates another button, and can create endless number of flashing buttons. Have an example that does more proper application logic, but still keep it simple.

Remove custom component. Currently, the application project stub includes a custom "**HelloButton**" JavaScript/Polymer component, and it is used in a somewhat odd way in the project stub. Creating a custom JS component is an advanced topic, makes the application stub unnecessarily complex, and should be in a separate project.

- [ ] Conventionalize the application logic
- [ ] Remove the custom component
- [ ] Revise Java template
- [ ] Revise Groovy template
- [ ] Revise Kotlin template
- [ ] Revise documentation that refers to the JS component

**Comment by mvysny** [comment]
As discussed with @mstahv the correct place for these stubs is in the Vaadin IDE plugin. We will remove support for generating source code. Solved when #18 is implemented.

**Comment by mvysny** [comment]
The project stubs will not be generated by the new plugin; the old plugin will be removed at some point. There is no point in fixing those project stubs. Marking as won't fix.
