### ISSUE TITLE
Vaadin Spring boot app webpack support (Vaadin 15) without any plugin ?

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/vaadin-gradle-plugin#56]
Solution provided by @caalador in https://github.com/vaadin/flow/issues/6277 unfortunately does not work with Vaadin 15. 

Gradle plugin https://github.com/vaadin/vaadin-gradle-plugin still does not support Vaadin 15.

How to modify approach from https://github.com/vaadin/flow/issues/6277 for Vaadin 15 ?

```
2020-04-04 07:54:59.542 [main] INFO  c.vaadin.flow.server.DevModeHandler - Running webpack to compile frontend resources. This may take a moment, please stand by...
...
i ｢wds｣: Project is running at http://localhost:60729/webpack-dev-server/
i ｢wds｣: webpack output is served from /VAADIN/
...
2020-04-04 07:33:25.298 [https-jsse-nio-8043-exec-1] ERROR v.c.v.l.KVaadinDefaultErrorHandler - Vaadin UI uncaught exception java.io.FileNotFoundException: http://localhost:60572/VAADIN/index.html
java.io.FileNotFoundException: http://localhost:60572/VAADIN/index.html
```
After I had copied (manually) index.html to <project-root>/VAADIN/, applications started, but only empty page displayed (e.g. Vaadin front-end didn't start)

**Comment by mvysny** [comment]
Thank you; this relates to #50 since it also discusses support for Vaadin 15. Please see a PR adding initial support for Vaadin 15 there as well.

**Comment by mvysny** [comment]
Since Vaadin 15 is no longer supported, we will not add support for it. However, support for Vaadin 17 is being pushed into master as we speak, so you will be able to use the plugin with Vaadin 17.

Please try the plugin with Spring on a Vaadin 17-based project; if there are any issues please file a new bug report.
