### ISSUE TITLE
Gradle vaadin plugin does not work with embedded jetty

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/vaadin-gradle-plugin#60]
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: 8
 - Gradle version: 6.3
 - Vaadin Plugin version: 0.6.0

**Describe the bug**
When using the gradle vaadin plugin with a small test project which uses embedded jetty, the resulting application does not launch properly.  Opening the localhost:8080 jetty root content shows a directly listing instead of the vaadin application.

See the README-Problem.txt in the attachment.

The attachment is based on a maven based example application available as: 
https://github.com/alejandro-du/embedded-jetty-demo.git

When launching this example using maven the embedded application is launched properly.  In the attachment the pom.xml has been "translated" to build.gradle with the com.vaadin plugin enabled.

[embedded-jetty-demo-gradle (2).zip](https://github.com/vaadin/vaadin-gradle-plugin/files/4555786/embedded-jetty-demo-gradle.2.zip)

**To Reproduce**
1. See README-Problem.txt in attachment

**Expected behavior**
Display "Does this work?" as button.

**Screenshots**

**Additional context**

**Comment by mvysny** [comment]
That sounds like the Vaadin Servlet was not auto-discovered by Jetty. Please try adding `context.addServlet(VaadinServlet.class, "/*");` into your `Application.java`. Your project is also pulling in webjars intended for the old bower mode, but that's only a secondary problem.

Please take a look at the following example app which demoes this use-case: https://github.com/mvysny/vaadin14-embedded-jetty-gradle

**Comment by mcooper7290** [comment]
I was able to get things working using the vaadin14-embedded-jetty-gradle example.

Thank you!
