### ISSUE TITLE
Vaadin 16 support

### ISSUE THREAD

**Issue by hfazai** [vaadin/vaadin-gradle-plugin#69]
**Desktop :**
 - OS: Fedora
 - JDK version: 8
 - Gradle version: 6.5
 - Vaadin Plugin version: 0.7.0

**Description of the bug**
I'm getting the below error when working with Vaadin 16 
`java.io.FileNotFoundException: http://localhost:60572/VAADIN/index.html`

**Expected**
It would be great if this plugin supports Vaadin 15/16

**Comment by mvysny** [comment]
Thank you for letting me know! The Vaadin 15 support request is at https://github.com/vaadin/vaadin-gradle-plugin/issues/50

**Comment by mvysny** [comment]
Since Vaadin 16 will get unsupported shortly, we will not add support for it. However, support for Vaadin 17 is being pushed into master as we speak, so you will be able to use the plugin with Vaadin 17.

**Comment by hfazai** [comment]
Ok @mvysny, supporting only Vaadin 17 is pretty fine as vaadin 16 will be deprecated soon.

I wanted to know if you have an estimate of when the new version of the plugin will be released?

**Comment by mvysny** [comment]
I finally managed to get the tests working and running :+1: I'll test the plugin on a very simple Vaadin17 project tomorrow; if everything works, I'll push for a release; hopefully tomorrow.
