### ISSUE TITLE
Remove compatibility mode

### ISSUE THREAD

**Issue by magi42** [vaadin/vaadin-gradle-plugin#7]
It's obsolete and can be removed.

If anyone wants to use it, can use the old plugin (a free version of it). Refer to using that.

**Comment by mvysny** [comment]
Actually the compatibility mode does not require any plugin at all - all that's needed is to add the compatibility.jar, vaadin-core and vaadin-pom as a dependency. The https://github.com/mvysny/karibu10-helloworld-application master branch at f9469c8d1080af3873c40af7ccf124847910a71d demonstrates this approach.

**Comment by mvysny** [comment]
Solved when #18 is implemented.

**Comment by mvysny** [comment]
The compatibility mode has been removed in 401b0e02b56e42288aff1ed4adbaf2b4f2ea4d8c
