### ISSUE TITLE
vaadinBuildFrontend vaadinPrepareFrontend caching?

### ISSUE THREAD

**Issue by JohnnyBeGood70** [vaadin/vaadin-gradle-plugin#70]
Hi,

Is there a way to force the use of a kind of cache for the above mentioned tasks. Both tasks takes quite long even if a small change was done in the code.

Thanks!

**Comment by mvysny** [comment]
Hi, the best way is to start using pnpm which is much faster than npm and caches stuff locally. To switch to pnpm:
1. Run gradle vaadinClean
2. Add vaadin { pnpm Enabled = true}
3. Build

Please see karibu10-helloworld-application for more details

**Comment by JohnnyBeGood70** [comment]
Hi Martin,

Thanks a lot. It works perfectly!
