### ISSUE TITLE
Spring Initializr does not add Vaadin Gradle Plugin line to build.gradle / build.gradle.kts plugins section

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/vaadin-gradle-plugin#94]
Could you communicate with maintainers of Spring Initializr to add 
id 'com.vaadin' version '0.8.0' to build.gradle 
id("com.vaadin") version "0.8.0" to build.gradle.kts

**Comment by mvysny** [comment]
Hmm I don't have this kind of power, but @mstahv could help?

**Comment by mvysny** [comment]
Thank you, filed upstream: https://github.com/spring-io/initializr/issues/1158

**Comment by mvysny** [comment]
Fixed upstream :+1:
