### ISSUE TITLE
compression-webpack-plugin switches versions on each run

### ISSUE THREAD

**Issue by magneticflux-** [vaadin/vaadin-gradle-plugin#95]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version: 11
 - Gradle version: 6.6.1
 - Vaadin Plugin version: `0.17.0.0`
 - Vaadin version: `17.0.3`

**Describe the bug**
Running the application in dev mode changes the version of `compression-webpack-plugin` between `3.1.0` and `4.0.1`. Each run changes the value to the opposite version.

**To Reproduce**
1. Setup project with IntelliJ IDEA
2. Run the project in debug mode
4. See check `package.json`

**Expected behavior**
The `package.json` should be static for a certain Vaadin version and plugin version.

**Comment by mvysny** [comment]
Hi, thank you for your report. I have tried a bit newer plugin `0.17.0.1` and Vaadin `17.0.7` and I'm no longer experiencing this issue. Could you please try to v-bump Vaadin and the plugin and try again? You can try the https://github.com/mvysny/karibu10-helloworld-application project, but please make sure to use the `master` branch.

**Comment by magneticflux-** [comment]
It looks like Vaadin `17.0.7` fixed the issue somehow. I'll reopen this if it happens again and we can try to track down the root cause then.
